ReDoS prevention
JefferyHus/es6-crawler-detect pull request #26
Opened 2020-12-05 23:09 UTC by exx8

This PR limits the user agent size which can be delivered to the lib.

We need to think if this limitation is too relaxed or too conservative.
This PR should not damage functionality.

2020-12-05 23:12 UTC, JefferyHus requested changes
Can you also add something to prevent consecutive characters?

This is the reason:

```
$ time node -e '/A(B|C+)+D/.test("ACCCCCCCCCCCCCCCCCCCCCCCCCCCCD")'
0.04s user 0.01s system 95% cpu 0.052 total

$ time node -e '/A(B|C+)+D/.test("ACCCCCCCCCCCCCCCCCCCCCCCCCCCCX")'
1.79s user 0.02s system 99% cpu 1.812 total
```

2020-12-05 23:13 UTC, JefferyHus commented
Thanks for the PR

2020-12-05 23:16 UTC, exx8 commented
We need to think what is a reasonable limitation of consecutive characters. like 5 characters?

2020-12-05 23:19 UTC, JefferyHus reviewed
> We need to think what is a reasonable limitation of consecutive characters. like 5 characters?

You can suggest. I believe we just need to do some tests to see the max consecutive limitation. Maybe we can write a function that will scan the safety of the `userAgent` string

2020-12-05 23:19 UTC, JefferyHus commented on src/lib/crawler.js
> +		if(Buffer.byteLength(userAgent, 'utf8')>4096)
Add some spaces here `if(Buffer.byteLength(userAgent, 'utf8') > 4096)`

2020-12-05 23:19 UTC, JefferyHus commented on src/lib/crawler.js
> +
Maybe run prettier? Added spaces here that should be removed

2020-12-05 23:46 UTC, exx8 commented
Sorry my friend, I currently don't have anymore to spend this PR in the following days.
Regarding the repeat you asked, you might want to get inspiration from this:
https://stackoverflow.com/a/15688386/14651383

2020-12-06 01:38 UTC, JefferyHus commented
> Sorry my friend, I currently don't have anymore time to spend this PR in the following days.
> Regarding the repeats you asked, you might want to get inspiration from this:
> https://stackoverflow.com/a/15688386/14651383

In that case I will merge what you did so far then work on the other features. Cheers

2020-12-06 01:39 UTC, merged